### ISSUE TITLE
CI for 0.27-maintenance not reporting test failures

### ISSUE THREAD

**Issue by piponazo** [Exiv2/exiv2#2022]
##### **Describe the bug**
In #2019 we noticed that the CI is not signaling error failures at the moment. 

##### **To Reproduce**
Current failures can be seen in the CI pipeline "Win Matrix on PRs":
https://github.com/Exiv2/exiv2/runs/4481561449?check_suite_focus=true#step:5:251

At the moment we just have noticed this one, but there might be more errors being silenced.

##### **Expected behavior**
CI should turn red (in order to avoid merging PRs) whenever a test fails. 

##### **Additional context**
I think the culprit of this situation is to use `cmake --build` to run the tests:

```
      - name: Test
        env:
          EXIV2_EXT: .exe
        run: |
          cd build
          cmake --build . --target tests
```
Probably `cmake --build` will succeed once the target is correctly built. On the `main` branch we are using CTest and I think CTest will correctly turn the CI job into red if a test fails:

```
      - name: Test
        if: ${{matrix.platform == 'x64'}}
        env:
          EXIV2_EXT: .exe
        run: |
          cd build
          ctest --output-on-failure
```

Note that it is not enough to use call `ctest` in the CI pipelines. We also need to port all the CTest configuration from `main` to `0.27-maintenance`.
